Repository HeathWallace/coinface, pull requests merged in 2018-03, with the labels that each got.

#103 Progress bar styling
  src/base.css
  src/components/Header/Header.css
  src/components/ProgressBar/ProgressBar.css
  src/components/ProgressBar/ProgressBar.js
  src/components/ProgressBar/wave.svg
  src/components/Transaction/Transaction.css
  src/components/Transaction/Transaction.js
  src/components/Transaction/Transaction.story.js
Labels: Status: Blocked

#120 Add multiple currencies and pending transactions
  .eslintrc.json
  src/actions/index.js
  src/actions/index.test.js
  src/actions/structures.js
  src/api/Api.js
  src/api/pending.js
  src/api/tokenMetadata.js
  src/api/transactions.js
  src/api/txHash.js
  src/components/NumberInput/NumberInput.js
  src/components/Transaction/Transaction.js
  src/components/TransactionsList/TransactionsList.js
  src/components/TrustSetting/TrustSetting.js
  src/constants/actionTypes.js
  src/containers/DailyTotal/DailyTotal.js
  src/containers/SettingsDrawer/SettingsDrawer.js
  src/containers/TransactionList/TransactionList.js
  src/index.js
  src/reducers/index.js
  src/reducers/slices/settings.js
  src/reducers/slices/tokens.js
  src/reducers/slices/transactions.js
  src/reducers/slices/transactions.test.js
  src/reducers/util.js
  src/utils/environment.js
Labels: :bar_chart: Type: Data, :small_red_triangle: Priority: High

#130 Added storybook/development section to README.md file
  README.md
Labels: :blue_book: Type: Documentation
