Repository HeathWallace/coinface, pull requests merged in 2018-02, with the labels that each got.

#47 Settings Wheel Component added to storybook
  .gitattributes
  src/components/SettingsWheel/SettingsWheel.css
  src/components/SettingsWheel/SettingsWheel.js
  src/components/SettingsWheel/SettingsWheel.png
  src/components/SettingsWheel/SettingsWheel.story.js
Labels: Priority: High, Status: Blocker

#49 Added list of binary filetypes to .gitattributes.
  .gitattributes
Labels: Priority: Critical, Type: Tooling, bug

#53 Identity wrapper component
  .gitignore
  src/components/Identity/Identity.js
  src/components/Identity/Identity.story.js
Labels: Type: Component

#67 Bugfix/production crashing on redux undefined
  src/index.js
  src/store.js
Labels: Priority: Critical, Type: Deployment

#71 Settings drawer styling
  src/App.css
  src/App.js
  src/base.css
  src/components/Header/Header.css
  src/components/SettingsDrawer/SettingsDrawer.css
  src/components/SettingsWheel/SettingsWheel.css
  src/components/SettingsWheel/SettingsWheel.png
  src/components/SettingsWheel/SettingsWheel.svg
  src/components/SettingsWheel/settings-256.png
  src/components/TransactionsList/TransactionsList.css
Labels: Type: UI
